name: CI
on:
  pull_request:

jobs:
  node-setup:
    name: Setup
    uses: ./.github/workflows/nodeSetup.yml
  ESLint:
    name: Check
    uses: ./.github/workflows/ESLint.yml
    needs: node-setup
  deploy-github-page:
    name: Github Page Deploy
    uses: ./.github/workflows/deployGithubPage.yml

