name: ESLint

on:
  workflow_call:

jobs:
  ESLint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node_modules-${{hashFiles('package-lock.json')}}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run ESLint
        run: npx eslint .
